### ISSUE TITLE
robot can not move

### ISSUE THREAD

**Issue by Dmzecho** [cpezzato/panda_simulation#1]
Hello,I meet a problem.My ubuntu version is 16.04 with gazebo 7.When I do "roslaunch panda_simulation simulation_single.launch",it works.But when doing "rosrun panda_control panda_control_AIC_single",the robot can't move.And there are no rostopics published.These are some screenshots:
![2019-11-28 17-14-52屏幕截图](https://user-images.githubusercontent.com/47681674/69793019-a2df5000-1202-11ea-9387-8caab798b9bf.png)
![2019-11-28 17-16-14屏幕截图](https://user-images.githubusercontent.com/47681674/69793119-cf936780-1202-11ea-9567-4bb2623240c1.png)
![2019-11-28 17-25-32屏幕截图](https://user-images.githubusercontent.com/47681674/69793825-2188bd00-1204-11ea-8b66-ec3f68d6153f.png)

What's more,I don't use the singularity image,is there any influence?
I would appreciate it if you could solve my problem.

**Comment by Linjackffy** [comment]
Do you click “play” button in the Gazebo GUI？

**Comment by cpezzato** [comment]
Sorry for the late reply, did you solve the issue? It might very well be the play button. You can also change that in the launch file and set the parameter ` <arg name="paused" default="false"/>`
